### PR TITLE
Update QueueMonitorResource to Fix and apply sorting

### PR DESCRIPTION
**Pull request by bcollins-oxford**
Sorting was applied to the form and not to the table.  Removed code from $form and applied to $table

### CODE REVIEW

**Comment by CodeWithDennis** [comment]
This should fix the issue =)

**Comment by CodeWithDennis** [comment]
This should fix the issue =)
Can you also make all the other columns sortable? (so we don't have to ask for another PR)

**Review by bcollins-oxford — COMMENTED** [review]
Adds sortable() to all columns

**Review by croustibat — COMMENTED** [review]
Nice ! thank you !

**Review by croustibat — APPROVED** [review]

**Pull request merged**
